### ISSUE TITLE
date range method

### ISSUE THREAD

**Issue by DeevD** [savvisingh/DateRangePicker#10]
hi bro calendar.getSelectedDates() is alwaay return empty array .. how to catch calendar change event?

**Comment by savvisingh** [comment]
Hey, can you tell me exactly what are you doing, so I can reproduce the bug.
There is no other method to get the selected dats.

**Comment by hienhtet** [comment]
oh i mean bro ...
calendar.getSelectedDates() this fun is always return empty []

**Comment by savvisingh** [comment]
it returns an ArrayList of Date Objects, cant seems to reproduce the error

**Comment by hienhtet** [comment]
ohnn bro how to get user selected dates ?

**Comment by savvisingh** [comment]
CalendarPickerView object has a method getSelectedDates

**Comment by savvisingh** [comment]
Can you post ur code snippet, how you are using it;

**Comment by hienhtet** [comment]
sorry bro i wrong i got this morning from calendar date array .. i miss some code bro ...thank you for nice library
