### ISSUE TITLE
getSelectedDates excluding highlighted and disabled dates

### ISSUE THREAD

**Issue by japx03** [savvisingh/DateRangePicker#16]
How do I get selected date range including highlighted and disabled dates in this library?

**Comment by savvisingh** [comment]
calendar.getSelectedDates() and exclude highlighted dates from it, its a bug I will try to fix it soon,
but for now you have to remove highlighted dates from selected date list yourself

**Comment by japx03** [comment]
How do I get the selected dates excluding the disabled days? I tried to
highlight from friday to monday where weekends were disabled and get the
selected dates it gives me 4 dates in an array

**Comment by savvisingh** [comment]
Hi I have updated the project this bug is fixed in com.savvi.datepicker:rangepicker:1.2.0
