### ISSUE TITLE
Current Date to Top Instead of Blank Space? 

### ISSUE THREAD

**Issue by 1nullpointer** [savvisingh/DateRangePicker#17]
Is there a way I can get the current Date To Top Of the Display ? 
If the **startDate for Initialization** is say end of the month(am selecting current Date) ,  is there a way to remove the blank space ? (screenshot Below)

![screen shot 2018-02-25 at 3 38 12 pm](https://user-images.githubusercontent.com/15132811/36640333-54f6e1f0-1a42-11e8-81bb-199f20274cf9.png)

**Comment by savvisingh** [comment]
I can fill that space with deactivated dates instead.

**Comment by savvisingh** [comment]
Please update your gradle dependency to the latest version com.savvi.datepicker:rangepicker:1.2.0

**Comment by 1nullpointer** [comment]
Working Nice . Thanks for the quick response !
