### ISSUE TITLE
Maximum and minimum range

### ISSUE THREAD

**Issue by rsalomao2** [savvisingh/DateRangePicker#27]
Is it possible to determine the maximum and minimum range that the user can select? i.e. 4 days only

**Comment by savvisingh** [comment]
Sry, I haven't covered this use case.
Maybe in future I will add this option

**Comment by vscotti** [comment]
I'd like to have this feature also. I hope soon we can have it.

**Comment by CoolMind** [comment]
@rsalomao2, @savvisingh, @vscotti Now you have this feature.

**Comment by savvisingh** [comment]
Hey hi, can you please share your code or raise a pr for this feature, so that others can use it.
Thanks
