### ISSUE TITLE
Locale issue

### ISSUE THREAD

**Issue by andreiacostinoaei** [savvisingh/DateRangePicker#33]
Hello! I got a question... Is it possible to set the Locale to be all the time Locale.US? If i change my device to Hebrew everything goes RTL and i can't stop that because when the calendar is initialized it picks all the time Locale.IW... is there a possibility to have device on Hebrew but save the calendar format to US? Thanks!

**Comment by savvisingh** [comment]
calendar.init(lastYear.getTime(), nextYear.getTime(), new SimpleDateFormat("MMMM, YYYY", Locale.getDefault()));

you can try passing the Locale.US in the initialization method instead of Locale.getDefault

**Comment by savvisingh** [comment]
You can change the locale in CalendarPickerView Class to Locale.US, I am using Locale.getDefault() in there. You have to copy the source code of the library in your project to do that.

And you can create locale as a param in initializer method, and send me a pull request.

**Comment by DaCodeShogun** [comment]
Changing locale didn't work. I changed the isRtl assignment in MonthView.java:
`view.isRtl = false; // isRtl(locale);`

**Comment by savvisingh** [comment]
hey sorry for the late reply, now you can pass locale as a param in init fun
init(Date minDate, Date maxDate, Locale locale)

**Comment by dudipsh** [comment]
> hey sorry for the late reply, now you can pass locale as a param in init fun
> init(Date minDate, Date maxDate, Locale locale)

this is fix the issue view.isRtl = false; // isRtl(locale);

thanks for the plugin
i try to add the new Locale('heb') 
its make the calendar in Hebrew but i have issue whit the rtl, 
its possible that you add the rtl on the init?
