### ISSUE TITLE
How can i add multiple date ranges.

### ISSUE THREAD

**Issue by flashfoxter** [savvisingh/DateRangePicker#36]
How can i add multiple date ranges, for example from 14-18 and 24-26 ? Thanks.

**Comment by nishchalraj** [comment]
I am afraid that this feature isn't there for now. BTW it will be amazing and also enhance the functionality of this library.

**Comment by savvisingh** [comment]
Hi as this is not an issue, I am moving this thread to feature requests.
And please update the new version and let me know of any bugs
