### ISSUE TITLE
Compiling correct but crashing on runtime

### ISSUE THREAD

**Issue by markuspaschi** [savvisingh/DateRangePicker#4]
Unable to start activity ComponentInfo{de..../de.....MainActivity}: android.view.InflateException: Binary XML file line #44: Binary XML file line #44: Error inflating class com.savvi.rangepicker.CalendarPickerView

 Didn't find class "com.savvi.rangepicker.CalendarPickerView" on path: DexPathList[[zip file "/data/app/de.....-2/base.apk"],nativeLibraryDirectories=[/data/app/de.....-2/lib/arm64, /data/app/de.....-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]

How can i fix this ?

Much appreciated 
Markus

**Comment by Axrorxoja** [comment]
use as library,not as via gradle

**Comment by kamiox** [comment]
@markuspaschi In the app/src/main/res/layout/activity_sample.xml rename com.savvi.rangepicker.CalendarPickerView to com.savvi.rangedatepicker.CalendarPickerView

**Comment by savvisingh** [comment]
Sorry for that, looks like I refactored the library and didn't changed my xml 👍
