### ISSUE TITLE
Display Year info

### ISSUE THREAD

**Issue by vinsbhat** [savvisingh/DateRangePicker#42]
It displays only month information. Display year info as well on the calendar

**Comment by CoolMind** [comment]
@vinsbhat See https://github.com/savvisingh/DateRangePicker/issues/9, https://github.com/savvisingh/DateRangePicker/issues/32. Also there is an error, not `SimpleDateFormat("MMMM, YYYY")`, but `SimpleDateFormat("MMMM yyyy")`.
