### ISSUE TITLE
Setting cell click listener

### ISSUE THREAD

**Issue by jerryHeld** [savvisingh/DateRangePicker#43]
I've set cellClickListener like that -
calendar.setCellClickInterceptor(new CalendarPickerView.CellClickInterceptor(){
            @Override
            public boolean onCellClicked(Date date) {
                //do some stuff
                return false;
            }
        });

What does the return value is using for? Whats the difference between returning true or false?

**Comment by savvisingh** [comment]
If you return true the calendar view will not select the dates it means that you have already handled the click and you don't want the calendar to handle it by default, otherwise if you return true the calendar view will select those dates
