### ISSUE TITLE
Selecting Date Range to the DatePicker from Dates in ArrayList

### ISSUE THREAD

**Issue by juzimmer** [savvisingh/DateRangePicker#49]
Currently I'm trying to SET a range of already saved dates to the DateRangePicker View upon the View becoming visible. I do see the selectDate(date) function but It is only working for 1 date at a time. I tried selecting the dates via for loop but it just selects the last date in my array list.

**Comment by alashow** [comment]
I think you can call init function with `withSelectedDates(savedDates)`.
