### ISSUE TITLE
Possible to assign individual dates with different colors at same time

### ISSUE THREAD

**Issue by juzimmer** [savvisingh/DateRangePicker#51]
I need the functionality to assign certain dates to certain colors , but they are all different color groups. Is there anyway to use highlight feature to achieve this or possibly changing the background color of each cell day to a color of my choice? 

Also, is there any way of making the date cells setOnDateSelectedListener clickable even for the highlighted dates ?

**Comment by Trixi-Turny** [comment]
^^ I would really like it if there was support for the above too. Especially making highlighted dates selectable. Is this currently possible?

**Comment by savvisingh** [comment]
Hi Sorry for the late response, as of now there is no callback for highlighted or deactivated dates, but will keep this features in next version, and do check the new 1.3.0 version of the lib
