### ISSUE TITLE
How to add separator line between two months ?

### ISSUE THREAD

**Issue by ArunVicky001** [savvisingh/DateRangePicker#54]
Hi 

Thanks you very much for the library, Could you please tell how add the separator line between two months like the below image
<img width="368" alt="Screenshot 2019-04-25 at 12 35 31 PM" src="https://user-images.githubusercontent.com/34921497/56715925-a2f00c80-6756-11e9-86b4-939426bc469f.png">

**Comment by ArunVicky001** [comment]
I made the changes in the library.

**Comment by savvisingh** [comment]
Hi there, can you please share your solution or better a pr so others can also use it.
Thanks

**Comment by ArunVicky001** [comment]
In the `month.xml` page I have added one separator line on top the  `CalendarGridView` and it's working awesome.
