### ISSUE TITLE
Hom to set local data and DateFormat

### ISSUE THREAD

**Issue by KreephetSathotnluk** [savvisingh/DateRangePicker#56]
calendar_view.init(lastYear.time, nextYear.time, SimpleDateFormat("MMMM YYYY", Locale("th","th")))
            .inMode(CalendarPickerView.SelectionMode.RANGE)
            .withSelectedDate(Date())
I'm set this is not 2568

**Comment by savvisingh** [comment]
Please use init(Date minDate, Date maxDate, TimeZone timeZone, Locale locale, DateFormat monthNameFormat) to specify different locale and timeZone, with custom month name format
