### ISSUE TITLE
Cannot override color resources

### ISSUE THREAD

**Issue by geouniq-android** [savvisingh/DateRangePicker#57]
Hi, I would override default color of selected days, I declared these color resources:
```xml
<color name="calendar_selected_day_bg">@color/colorPrimary</color>
<color name="calendar_selected_range_bg">@color/colorPrimary</color>
<color name="dateTimeRangePickerStateToday">@color/colorPrimary</color>
```
The text color of "Today" change correctly, but the color of selected days remains as default color(yellow), how I can change it? Thanks

**Comment by savvisingh** [comment]
Hi I will be updating this shortly

**Comment by savvisingh** [comment]
Hi Please check the new version of the lib 1.3.0 and you can find the info in ReadMe on how to override the default colors

**Comment by geouniq-android** [comment]
Thank you!
