### ISSUE TITLE
WeekDays name not in english

### ISSUE THREAD

**Issue by MuhammadNoor10** [savvisingh/DateRangePicker#58]
I just followed the instructions to implement DateRangePicker(This library). But once i set up everything my weekdays names are not in english. How can i change that to in enlgish?

**Comment by savvisingh** [comment]
calendar.init(lastYear.getTime(), nextYear.getTime(), new SimpleDateFormat("MMMM, YYYY", Locale.getDefault()));

pass your locale in init method

**Comment by MuhammadNoor10** [comment]
Yeah thanks @savvisingh for your time and reply. Actually i did solve it by myself. I just looked into library classes then i get to know to pass locale according to your requirement. I'm closing this issue.
