### ISSUE TITLE
Commented method to select dates

### ISSUE THREAD

**Issue by Gralls** [savvisingh/DateRangePicker#6]
Hi i found in CalendarPickerView at line 290 that you commented method to select dates. Is this any reasons for that or just misstake? Becouse of that methods like withSelectedDates doesn't work as expected.

**Comment by savvisingh** [comment]
ya sorry for that, looks like I commented it for no reason
you can try that method uncommented and let me know if you runs into any error.
👍

**Comment by Gralls** [comment]
I checked that and it looks ok, givens dates are selected properly ;)

**Comment by grennis** [comment]
@Gralls  Maybe send a PR :)
