### ISSUE TITLE
why have not year?

### ISSUE THREAD

**Issue by Hankkin** [savvisingh/DateRangePicker#9]

**Comment by savvisingh** [comment]
Thanks for reminding, I will add it

**Comment by savvisingh** [comment]
Hi there I have added monthHeader DateFormat object in constructor so that you can show year also.

`calendar.init(lastYear.getTime(), nextYear.getTime(), new SimpleDateFormat("MMMM, YYYY", Locale.getDefault()));`

And update the library to com.savvi.datepicker:rangepicker:1.2.0
